
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      base_branch:
        description: "Base branch to diff against (only used when cargo_deny_check=auto)"
        type: string
        default: master
      cargo_deny_check:
        description: "Run or skip the `cargo deny` step"
        type: choice
        options:
          - auto
          - force-run
          - force-skip
        default: auto

name: Check, Lint, Build

env:
  CARGO_TERM_COLOR: always
  ELECTRS_VERSION: v3.2.0

jobs:
  check-lint:
    name: Check, Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      
      - name: Install latest nightly toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt, clippy

      - name: Restore Rust cache
        id: restore-rust-cache
        uses: Swatinem/rust-cache@v2.9.1
        with:
          cache-all-crates: "true"
          prefix-key: "v0-rust-nightly"
          save-if: "false"
          shared-key: debug-x86_64-unknown-linux-gnu

      - name: Save Rust cache
        if: steps.restore-rust-cache.outputs.cache-hit != 'true'
        uses: Swatinem/rust-cache@v2.9.1
        with:
          cache-all-crates: "true"
          lookup-only: "true"
          prefix-key: "v0-rust-nightly"
          shared-key: debug-x86_64-unknown-linux-gnu

      - name: Rustfmt
        run: cargo fmt --all -- --check
      
      - name: Cargo check
        run: cargo check --all-targets --all-features
      
      - name: Clippy
        run: cargo clippy --all-targets --all-features
      
      - name: Check changed files
        id: changed-files
        if: github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && inputs.cargo_deny_check == 'auto')
        uses: dorny/paths-filter@v4
        with:
          filters: |
            cargo_lock:
              - 'Cargo.lock'
            deny_toml:
              - 'deny.toml'

      - name: Deny
        if: >-
          (github.event_name == 'pull_request' && (steps.changed-files.outputs.cargo_lock == 'true' || steps.changed-files.outputs.deny_toml == 'true')) ||
          (github.event_name == 'workflow_dispatch' && inputs.cargo_deny_check == 'force-run') ||
          (github.event_name == 'workflow_dispatch' && inputs.cargo_deny_check == 'auto' && (steps.changed-files.outputs.cargo_lock == 'true' || steps.changed-files.outputs.deny_toml == 'true'))
        uses: EmbarkStudios/cargo-deny-action@v2

  cache-electrs:
    name: Build electrs if not cached
    runs-on: ubuntu-latest
    steps:
      - name: Check cache
        id: check-cache
        uses: actions/cache/restore@v6
        with:
          lookup-only: true
          path: ${{ runner.temp }}/electrs/target/release/electrs
          key: electrs-${{ env.ELECTRS_VERSION }}

      - name: Build electrs
        if: steps.check-cache.outputs.cache-hit != 'true'
        run: |
          git clone --branch ${{ env.ELECTRS_VERSION }} --depth 1 https://github.com/mempool/electrs.git ${{ runner.temp }}/electrs
          pushd ${{ runner.temp }}/electrs
          cargo build --locked --release
          popd

      - name: Save cache
        if: steps.check-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v6
        with:
          path: ${{ runner.temp }}/electrs/target/release/electrs
          key: electrs-${{ env.ELECTRS_VERSION }}


  integration-test:
    name: Integration test
    runs-on: ubuntu-latest
    needs: [cache-electrs, check-lint]
    steps:
      - name: Download latest bitcoin-patched
        run: |
          pushd ..
          wget https://releases.drivechain.info/L1-bitcoin-patched-latest-x86_64-unknown-linux-gnu.zip
          unzip L1-bitcoin-patched-latest-x86_64-unknown-linux-gnu.zip
          rm L1-bitcoin-patched-latest-x86_64-unknown-linux-gnu.zip
          mv L1-bitcoin-patched-latest-x86_64-unknown-linux-gnu bitcoin-patched-bins
          chmod +x bitcoin-patched-bins/bitcoind
          chmod +x bitcoin-patched-bins/bitcoin-cli
          popd

      - name: Download bitcoin unpatched
        run: |
          pushd ..
          wget https://bitcoincore.org/bin/bitcoin-core-30.2/bitcoin-30.2-x86_64-linux-gnu.tar.gz
          tar -xf bitcoin-30.2-x86_64-linux-gnu.tar.gz
          rm bitcoin-30.2-x86_64-linux-gnu.tar.gz
          mv bitcoin-30.2/bin bitcoin-unpatched-bins
          rm -r bitcoin-30.2
          popd

      - name: Download latest bip300301_enforcer
        run: |
          pushd ..
          wget https://releases.drivechain.info/bip300301-enforcer-latest-x86_64-unknown-linux-gnu.zip
          unzip bip300301-enforcer-latest-x86_64-unknown-linux-gnu.zip
          rm bip300301-enforcer-latest-x86_64-unknown-linux-gnu.zip
          mv bip300301-enforcer-latest-x86_64-unknown-linux-gnu/bip300301-enforcer-*-x86_64-unknown-linux-gnu bip300301-enforcer
          rm -r bip300301-enforcer-latest-x86_64-unknown-linux-gnu
          chmod +x bip300301-enforcer
          popd

      - name: Restore electrs from cache
        uses: actions/cache/restore@v6
        with:
          fail-on-cache-miss: true
          path: ${{ runner.temp }}/electrs/target/release/electrs
          key: electrs-${{ env.ELECTRS_VERSION }}

      - uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - name: Install latest nightly toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.9.1
        with:
          cache-all-crates: "true"
          prefix-key: "v0-rust-nightly"
          shared-key: debug-x86_64-unknown-linux-gnu

      - name: Build (debug)
        run: cargo build --bin thunder_app --example integration_tests

      - name: Run integration tests
        id: runIntegrationTests
        run: |
          export BIP300301_ENFORCER='../bip300301-enforcer'
          export BITCOIND='../bitcoin-patched-bins/bitcoind'
          export BITCOIND_UNPATCHED='../bitcoin-unpatched-bins/bitcoind'
          export BITCOIN_CLI='../bitcoin-patched-bins/bitcoin-cli'
          export ELECTRS='${{ runner.temp }}/electrs/target/release/electrs'
          export THUNDER_APP='target/debug/thunder_app'
          target/debug/examples/integration_tests

  test-build-release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: x86_64-unknown-linux-gnu
            binary-suffix: ""
            rustflags: ""
          - os: macos-latest-large
            name: x86_64-apple-darwin
            binary-suffix: ""
            rustflags: ""
          - os: macos-latest
            name: aarch64-apple-darwin
            binary-suffix: ""
            rustflags: ""
          - os: ubuntu-latest
            name: x86_64-pc-windows-gnu
            binary-suffix: .exe
            rustflags: "-C linker=/usr/bin/x86_64-w64-mingw32-gcc"
    name: Test, Build, Release ((${{ matrix.name }}))
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    timeout-minutes: 20
    steps:
      - name: Install windows-specific deps
        run: sudo apt install mingw-w64
        if: ${{ matrix.name == 'x86_64-pc-windows-gnu' }}

      - uses: actions/checkout@v6
        with:
          submodules: recursive
      
      - name: Install latest nightly toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          target: ${{ matrix.name }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.9.1
        with:
          cache-all-crates: "true"
          prefix-key: "v0-rust-nightly"
          shared-key: ${{ matrix.name }}

      - name: Test
        run: cargo test --tests

      - name: Build
        run: cargo build --release --target ${{ matrix.name }}
        env:
          RUSTFLAGS: ${{ matrix.rustflags }}

      - name: 'Set environment variables: version number and output filenames'
        run: |
          THUNDER_APP_VERSION=$(cargo metadata --format-version 1 | \
            jq -er '.packages | map(select(.name == "thunder_app") | .version) | .[0]')
          THUNDER_APP_FILENAME="thunder-${THUNDER_APP_VERSION}-${{ matrix.name }}${{ matrix.binary-suffix }}"
          THUNDER_CLI_FILENAME="thunder-cli-${THUNDER_APP_VERSION}-${{ matrix.name }}${{ matrix.binary-suffix }}"
          echo "THUNDER_APP_VERSION=$THUNDER_APP_VERSION" >> "$GITHUB_ENV"
          echo "THUNDER_APP_FILENAME=$THUNDER_APP_FILENAME" >> "$GITHUB_ENV"
          echo "THUNDER_CLI_FILENAME=$THUNDER_CLI_FILENAME" >> "$GITHUB_ENV"

      - name: 'Set filenames for release binaries'
        run: |
          pushd "target/${{ matrix.name }}/release/"
          ln -fs "thunder_app${{ matrix.binary-suffix }}" "${THUNDER_APP_FILENAME}"
          ln -fs "thunder_app_cli${{ matrix.binary-suffix }}" "${THUNDER_CLI_FILENAME}"
          popd

      - name: 'Upload Artifacts (thunder)'
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.THUNDER_APP_FILENAME }}
          if-no-files-found: error
          path: |
            target/${{ matrix.name }}/release/${{ env.THUNDER_APP_FILENAME }}
            target/${{ matrix.name }}/release/${{ env.THUNDER_CLI_FILENAME }}

      - name: Extract Git tag name
        id: git-tag-name
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "git_tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Parse Git tag name as semver
        uses: madhead/semver-utils@v5.0.0
        if: startsWith(github.ref, 'refs/tags/')
        id: parse-git-tag-name-semver
        with:
          version: ${{ steps.git-tag-name.outputs.git_tag_name }}

      - name: Release
        uses: softprops/action-gh-release@v3.0.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/${{ matrix.name }}/release/${{ env.THUNDER_APP_FILENAME }}
            target/${{ matrix.name }}/release/${{ env.THUNDER_CLI_FILENAME }}
          fail_on_unmatched_files: true
          prerelease: ${{ steps.parse-git-tag-name-semver.outputs.prerelease != '' }}

  parse-semver:
    name: Parse version info
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    outputs:
      prerelease: ${{ steps.parse-git-tag-name-semver.outputs.prerelease }}
    steps:
      - name: Extract Git tag name
        id: git-tag-name
        run: |
          echo "git_tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Parse Git tag name as semver
        uses: madhead/semver-utils@v5.0.0
        id: parse-git-tag-name-semver
        with:
          version: ${{ steps.git-tag-name.outputs.git_tag_name }}

  upload-releases-to-releases-drivechain-info:
    name: Upload releases to releases.drivechain.info
    runs-on: ubuntu-latest
    needs: [integration-test, test-build-release, parse-semver]
    if: startsWith(github.ref, 'refs/tags/') && needs.parse-semver.outputs.prerelease == ''
    steps:
      - name: Download release assets
        uses: robinraju/release-downloader@v1.13
        with:
          fileName: '*'
          tag: ${{ github.ref_name }}

      - name: Create zip files for releases.drivechain.info
        run: |
          shopt -s extglob
          mv thunder-+([0-9]).+([0-9]).+([0-9])-x86_64-apple-darwin thunder-latest-x86_64-apple-darwin
          mv thunder-cli-+([0-9]).+([0-9]).+([0-9])-x86_64-apple-darwin thunder-cli-latest-x86_64-apple-darwin
          zip L2-S9-Thunder-latest-x86_64-apple-darwin.zip \
            thunder-latest-x86_64-apple-darwin \
            thunder-cli-latest-x86_64-apple-darwin
          mv thunder-+([0-9]).+([0-9]).+([0-9])-aarch64-apple-darwin thunder-latest-aarch64-apple-darwin
          mv thunder-cli-+([0-9]).+([0-9]).+([0-9])-aarch64-apple-darwin thunder-cli-latest-aarch64-apple-darwin
          zip L2-S9-Thunder-latest-aarch64-apple-darwin.zip \
            thunder-latest-aarch64-apple-darwin \
            thunder-cli-latest-aarch64-apple-darwin
          mv thunder-+([0-9]).+([0-9]).+([0-9])-x86_64-pc-windows-gnu.exe thunder-latest-x86_64-pc-windows-gnu.exe
          mv thunder-cli-+([0-9]).+([0-9]).+([0-9])-x86_64-pc-windows-gnu.exe thunder-cli-latest-x86_64-pc-windows-gnu.exe
          zip L2-S9-Thunder-latest-x86_64-pc-windows-gnu.zip \
            thunder-latest-x86_64-pc-windows-gnu.exe \
            thunder-cli-latest-x86_64-pc-windows-gnu.exe
          mv thunder-+([0-9]).+([0-9]).+([0-9])-x86_64-unknown-linux-gnu thunder-latest-x86_64-unknown-linux-gnu
          mv thunder-cli-+([0-9]).+([0-9]).+([0-9])-x86_64-unknown-linux-gnu thunder-cli-latest-x86_64-unknown-linux-gnu
          zip L2-S9-Thunder-latest-x86_64-unknown-linux-gnu.zip \
            thunder-latest-x86_64-unknown-linux-gnu \
            thunder-cli-latest-x86_64-unknown-linux-gnu

      - name: Upload release assets to releases.drivechain.info
        uses: appleboy/scp-action@v1
        with:
          host: 45.33.96.47
          username: root
          password: ${{ secrets.RELEASES_SERVER_PW }}
          port: 22
          source: 'L2-S9-Thunder-latest-*.zip'
          target: '/var/www/html/'
